export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';

export const LOADING_MEDICINES = 'LOADING_MEDICINES'
export const ERROR_MEDICINES = 'ERROR_MEDICINES'
export const GET_MEDICINE = 'GET_MEDICINE';
export const ADD_MEDICINE = 'ADD_MEDICINE';
export const DELETE_MEDICINE = 'DELETE_MEDICINE';
export const UPDATE_MEDICINE = 'UPDATE_MEDICINE';


export const GET_PATIENTS = "GET_PATIENTS";
export const ERROR_PATIENTS = 'ERROR_PATIENTS';
export const LOADING_PATIENTS = 'LOADING_PATIENTS';
export const ADD_PATIENTS = "ADD_PATIENTS";
export const DELETE_PATIENTS= 'DELETE_PATIENTS';
export const UPDATE_PATIENTS = 'UPDATE_PATIENTS';


export const GET_DOCTORS = "GET_DOCTORS";
export const ERROR_DOCTORS= "ERROR_DOCTORS"
export const ADD_DOCTORS ="ADD_DOCTORS";
export const DELETE_DOCTORS ="DELETE_DOCTORS";
export const UPDATE_DOCTORS ="UPDATE_DOCTORS";

